project:
  type: book
  output-dir: docs

book:
  title: "STA238 Lecture Notes"
  author: "Emily Somerset"
  chapters:
    - index.qmd
    - lec01.qmd
    - lec02.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  pdf:
    toc: true
    number-sections: true
    output-file: sta238-notes.pdf
