project:
  type: website
  output-dir: docs

website:
  title: "STA238 Lecture Notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lec01.qmd
        text: Lecture 1
      - href: lec02.qmd
        text: Lecture 2

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  pdf:
    toc: true
    number-sections: true
